### ISSUE TITLE
contact the original author

### ISSUE THREAD

**Issue by gonewest818** [gonewest818/osx-plist#1]
Reaching out to @hober (the author) and @ferdy (who has a mirror here on github) to ask if they have any objections to my publishing this updated version to MELPA?

**Comment by hober** [comment]
Hi! I suppose that's fine. I haven't changed the library in ages, though. What's changed?

**Comment by gonewest818** [comment]
Hi, and thanks for replying.   Here's the change log:
- Complete support for plist types: integer, real, date, and base64 data
- CircleCI pipeline including lint, test cases, and coverage analysis
- Breaking change: drop environment.plist example code

The reason for the third bullet is because OSX 10.8 and newer no longer supports setting environment variables in a "~/.MacOSX/environment.plist" so the example of using this code to bootstrap one's environment is a bit anachronistic... I removed that code but mention there is a newer package that sets up your environment variables a different way and seems to work well.

**Comment by hober** [comment]
Sounds awesome! Please do update MELPA!

**Comment by gonewest818** [comment]
Ok, will do.  Thanks for getting back to me!
